In [3]:
import numpy as np

In [10]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.arange(n**2).reshape(n,n)
n_size_ndarray_creation(5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if(type==0):
        return np.zeros(shape)
    elif(type==1):
        return np.ones(shape)
    elif(type==99):
        return np.empty(shape)

zero_or_one_or_empty_ndarray(shape=(2,2), type=1)
#array([[ 1,  1],
 #       [ 1,  1]])

array([[1., 1.],
       [1., 1.]])

In [18]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)
#임의의수 생성

array([[0.00000000e+000, 2.25293935e-321, 2.47032823e-323],
       [6.83298937e-312, 0.00000000e+000, 2.47032823e-323],
       [6.83298942e-312, 0.00000000e+000, 3.23815565e-319]])

In [22]:
def change_shape_of_ndarray(X, n_row):
    return X.reshape(n_row, -1)

X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 1)

array([[1, 1, 1, ..., 1, 1, 1]])

In [23]:
change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [110]:
def concat_ndarray(X_1, X_2, axis):
    if(X_1.ndim==1):  X_1 = np.asmatrix(X_1)
    if(X_2.ndim==1):  X_2 = np.asmatrix(X_2)
        
    if(X_1.T.shape[axis]==X_2.T.shape[axis]):
        return np.concatenate((X_1, X_2), axis)
    else:
        return False

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 0)

(2, 2)
(1, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
concat_ndarray(a,b,1)

(2, 2)
(1, 2)


False

In [113]:
a = np.array([1, 2])
b = np.array([5, 6, 7])
concat_ndarray(a, b, 0)

(1, 2)
(1, 3)


False

In [261]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis==99:
        return (X - np.mean(X)) /np.std(X)
    elif(axis==0):
        return (np.mean(X, axis)-X)/np.std(X,axis)
    else:
        return ((np.mean(X, axis)-X.T)/np.std(X,axis)).T

In [262]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
normalize_ndarray(X)

array([[-1.593255  , -1.3035723 ],
       [-1.0138896 , -0.7242068 ],
       [-0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ],
       [ 0.7242068 ,  1.0138896 ],
       [ 1.3035723 ,  1.593255  ]], dtype=float32)

In [263]:
normalize_ndarray(X,0)

array([[ 1.46385,  1.46385],
       [ 0.87831,  0.87831],
       [ 0.29277,  0.29277],
       [-0.29277, -0.29277],
       [-0.87831, -0.87831],
       [-1.46385, -1.46385]], dtype=float32)

In [264]:
(np.mean(X,1)-X.T).T
np.mean(X,1).reshape(len(X),1)-X
normalize_ndarray(X,1)

array([[ 1., -1.],
       [ 1., -1.],
       [ 1., -1.],
       [ 1., -1.],
       [ 1., -1.],
       [ 1., -1.]], dtype=float32)

In [193]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename,X)
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename) #test.npy 파일이 생성됨

In [265]:
def boolean_index(X, condition):
    return np.where(eval("X"+condition))

X = np.arange(32, dtype=np.float32).reshape(4, -1)
boolean_index(X, "== 3")

(array([0], dtype=int64), array([3], dtype=int64))

In [266]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [225]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]
X = np.random.uniform(0, 1, 100)
target_value = 0.3
find_nearest_value(X, target_value)

0.31503751178914186

In [232]:
def get_n_largest_values(X, n):
    return -np.sort(-X)[:n]

np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

array([0.99424396, 0.99365931, 0.97907263])